# Generated by Django 5.0.6 on 2025-07-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="concert.area"
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "name")},
            },
        ),
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "kopis_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("prfnm", models.CharField(max_length=250)),
                ("datetime", models.DateTimeField()),
                ("prfruntime", models.CharField(max_length=10)),
                ("price", models.CharField(max_length=250)),
                ("prfcast", models.CharField(default="", max_length=250)),
                ("display_poster_name", models.CharField(default="", max_length=250)),
                ("program_blurb", models.CharField(default="", max_length=1000)),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areas",
                        to="concert.area",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="concert.facility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FullPosterName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="full_poster_names",
                        to="concert.concert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Performer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performers",
                        to="concert.concert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("composer", models.CharField(max_length=250)),
                ("work", models.CharField(max_length=250)),
                ("composer_fuzzy_match_confidence", models.FloatField(default=0.0)),
                ("work_fuzzy_match_confidence", models.FloatField(default=0.0)),
                (
                    "composer_fuzzy_match",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.composer",
                    ),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="concert.concert",
                    ),
                ),
                (
                    "work_fuzzy_match",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.work",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("url", models.URLField(max_length=250)),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_vendors",
                        to="concert.concert",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="concert",
            constraint=models.UniqueConstraint(
                fields=("kopis_id", "datetime"),
                name="kopis_id_datetime_unique_combination",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fullpostername",
            unique_together={("concert", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="performer",
            unique_together={("concert", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="ticketvendor",
            unique_together={("concert", "name", "url")},
        ),
    ]
