# Generated by Django 5.0.6 on 2025-07-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="composer_fuzzy_match_confidence",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="concert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="concert.concert",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="work_fuzzy_match_confidence",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
