# Generated by Django 5.0.6 on 2025-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_alter_program_composer_fuzzy_match_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='display_poster',
            field=models.ImageField(blank=True, null=True, upload_to='display_poster/'),
        ),
        migrations.AddField(
            model_name='concert',
            name='full_poster',
            field=models.ImageField(blank=True, null=True, upload_to='full_poster/'),
        ),
    ]
