# Generated by Django 5.0.6 on 2025-07-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_concert_display_poster_concert_full_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullpostername',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='full_poster/'),
        ),
    ]
