# Generated by Django 5.0.6 on 2025-07-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("name_ko", models.TextField(blank=True, null=True)),
                ("lastname_ko", models.TextField(blank=True, null=True)),
                ("complete_name", models.TextField(blank=True, null=True)),
                ("portrait", models.TextField(blank=True, null=True)),
                ("birth", models.DateField()),
                ("death", models.DateField(blank=True, null=True)),
                ("epoch", models.TextField()),
                ("country", models.TextField(blank=True, null=True)),
                ("recommended", models.BooleanField(blank=True, null=True)),
                ("popular", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("title_ko", models.TextField(blank=True, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("subtitle_ko", models.TextField(blank=True, null=True)),
                ("searchterms", models.TextField(blank=True, null=True)),
                ("genre", models.TextField()),
                ("year", models.DateField(blank=True, null=True)),
                ("recommended", models.BooleanField(blank=True, null=True)),
                ("popular", models.BooleanField(blank=True, null=True)),
                (
                    "composer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.composer",
                    ),
                ),
            ],
        ),
    ]
